const CONFIG_KEY='ky5_sync_config';
const META_KEY='ky5_sync_meta';
const DEFAULT_CONFIG={endpoint:'https://lkhfdjbavyylzerogyun.supabase.co',anonKey:'sb_publishable_72R3k2970zgxToYj1QIgWQ_s4oqdHTE'};
const DATA_KEYS=['ky5_state','ky5_settings','ky5_pool','ky5_quiz','ky5_reading','ky5_sentence','ky5_sentence_context','ky5_sentence_history','ky5_exam_text','ky5_theme'];
const encoder=new TextEncoder(),decoder=new TextDecoder();
import{localDateKey,localDayStart,timestampValue}from'./date-utils.js?v=6.0.0';
import{upgradeMemoryRecord,memoryStage}from'./memory-engine.js?v=6.1.1';

const parse=(value,fallback=null)=>{try{return JSON.parse(value)??fallback}catch{return fallback}};
const b64=bytes=>{let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s)};
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const normalizedEndpoint=value=>String(value||'').trim().replace(/\/+$/,'');

export function getSyncConfig(){return{...DEFAULT_CONFIG,...(parse(localStorage.getItem(CONFIG_KEY),{})||{})}}
export function saveSyncConfig(config){const next={endpoint:normalizedEndpoint(config.endpoint||DEFAULT_CONFIG.endpoint),anonKey:String(config.anonKey||DEFAULT_CONFIG.anonKey).trim(),syncId:String(config.syncId||'').trim(),passphrase:String(config.passphrase||''),autoSync:config.autoSync!==false};localStorage.setItem(CONFIG_KEY,JSON.stringify(next));return next}
export function clearSyncConfig(){localStorage.removeItem(CONFIG_KEY);localStorage.removeItem(META_KEY)}
export function isConfigured(config=getSyncConfig()){return Boolean(config.endpoint&&config.anonKey&&config.syncId&&config.passphrase?.length>=8)}
export function createSyncId(){return crypto.randomUUID?.()||`${Date.now().toString(36)}-${b64(crypto.getRandomValues(new Uint8Array(18))).replace(/[+/=]/g,'').toLowerCase()}`}

export function snapshot(){const data={};for(const key of DATA_KEYS){const value=localStorage.getItem(key);if(value!==null)data[key]=parse(value,value)}return{version:2,savedAt:Date.now(),data}}

function latestRecord(a={},b={}){
  const left=upgradeMemoryRecord(a),right=upgradeMemoryRecord(b),at=Math.max(timestampValue(left.updatedAt),timestampValue(left.lastSeen)),bt=Math.max(timestampValue(right.updatedAt),timestampValue(right.lastSeen)),recent=bt>at?right:left,today=localDateKey();
  const todayDoneDate=left.todayDoneDate===today||right.todayDoneDate===today?today:recent.todayDoneDate,todayExposedDate=left.todayExposedDate===today||right.todayExposedDate===today?today:recent.todayExposedDate,todayRecalledDate=left.todayRecalledDate===today||right.todayRecalledDate===today?today:recent.todayRecalledDate;
  const leftFail=timestampValue(left.lastFailedAt),rightFail=timestampValue(right.lastFailedAt),leftPass=timestampValue(left.lastPassedAt),rightPass=timestampValue(right.lastPassedAt),newestFail=Math.max(leftFail,rightFail),newestPass=Math.max(leftPass,rightPass),cycleStartedAt=Math.max(timestampValue(left.cycleStartedAt),timestampValue(right.cycleStartedAt)),cycleRecords=cycleStartedAt?[left,right].filter(record=>timestampValue(record.cycleStartedAt)===cycleStartedAt):[left,right];
  const exposureDates=[...new Set([...(left.exposureDates||[]),...(right.exposureDates||[])])].sort().slice(-120),recallPassDates=[...new Set(cycleRecords.flatMap(record=>record.recallPassDates||[]))].sort(),contextPassDates=[...new Set(cycleRecords.flatMap(record=>record.contextPassDates||[]))].sort(),recallHistoryDates=[...new Set([...(left.recallHistoryDates||[]),...(right.recallHistoryDates||[])])].sort().slice(-120),contextHistoryDates=[...new Set([...(left.contextHistoryDates||[]),...(right.contextHistoryDates||[])])].sort().slice(-120);
  const merged={...left,...right,...recent,drawn:Boolean(left.drawn||right.drawn),errors:Math.max(left.errors||0,right.errors||0),lapses:Math.max(left.lapses||0,right.lapses||0),recognitionCount:Math.max(left.recognitionCount||0,right.recognitionCount||0),acquisitionSuccessCount:Math.max(left.acquisitionSuccessCount||0,right.acquisitionSuccessCount||0),acquisitionMisses:Math.max(left.acquisitionMisses||0,right.acquisitionMisses||0),correctStreak:Number(recent.correctStreak||0),cycleStartedAt,exposureDates,recallPassDates,contextPassDates,recallHistoryDates,contextHistoryDates,todayDoneDate,todayExposedDate,todayRecalledDate,slain:Boolean(recent.slain),favorite:Boolean(recent.favorite)};
  if(newestFail>=newestPass){merged.needsRelearning=true;merged.masteredAt=null;merged.tailStage=false;merged.correctStreak=0}
  const stage=memoryStage(merged);merged.tailStage=stage==='mastered';merged.level=stage==='mastered'?4:stage==='recall'||stage==='context'?3:stage==='recognition'?2:stage==='relearning'?1:0;return merged;
}
function mergeState(local={},remote={}){const records={...local.records};for(const[word,value]of Object.entries(remote.records||{}))records[word]=latestRecord(records[word],value);const history={...remote.history,...local.history};for(const d of new Set([...Object.keys(local.history||{}),...Object.keys(remote.history||{})]))history[d]=Math.max(local.history?.[d]||0,remote.history?.[d]||0);const localDate=local.lastStudyDate||'',remoteDate=remote.lastStudyDate||'';return{...remote,...local,records,history,rounds:{gaokao:Math.max(local.rounds?.gaokao||1,remote.rounds?.gaokao||1),kaoyan:Math.max(local.rounds?.kaoyan||1,remote.rounds?.kaoyan||1)},lastStudyDate:localDate>=remoteDate?localDate:remoteDate,streak:Math.max(local.streak||0,remote.streak||0)}}
function mergeSettings(local={},remote={}){return timestampValue(remote.updatedAt)>timestampValue(local.updatedAt)?remote:local}
function mergePool(local,remote){if(!local)return remote;if(!remote)return local;if(local.date!==remote.date)return(local.date||'')>(remote.date||'')?local:remote;if(local.mode!==remote.mode)return Number(remote.updatedAt||0)>Number(local.updatedAt||0)?remote:local;const lc=local.completed?.length||0,rc=remote.completed?.length||0,base=lc===rc?(Number(remote.updatedAt||0)>Number(local.updatedAt||0)?remote:local):(lc>rc?local:remote),manual=[...new Set([...(local.manual||[]),...(remote.manual||[])])];return{...base,items:[...new Set([...(base.items||[]),...manual])],completed:[...new Set([...(local.completed||[]),...(remote.completed||[])])],locked:[...new Set([...(local.locked||[]),...(remote.locked||[])])],manual,updatedAt:Math.max(local.updatedAt||0,remote.updatedAt||0)}}
function mergeQuiz(local={},remote={}){const out={...remote,...local};for(const date of new Set([...Object.keys(local||{}),...Object.keys(remote||{})])){const attempts=[...(remote?.[date]?.attempts||[]),...(local?.[date]?.attempts||[])],seen=new Set();out[date]={...(remote?.[date]||{}),...(local?.[date]||{}),attempts:attempts.filter(x=>{const key=x.id||`${x.at}-${x.score}-${x.total}`;if(seen.has(key))return false;seen.add(key);return true}).sort((a,b)=>(a.at||0)-(b.at||0))}}return out}
function mergeList(local=[],remote=[]){const out=[],seen=new Set();for(const item of [...local,...remote].sort((a,b)=>(b.at||0)-(a.at||0))){const key=item.id||item.sentence;if(!key||seen.has(key))continue;seen.add(key);out.push(item)}return out.slice(0,100)}
function recoverTodayPool(data){const today=localDateKey(),start=localDayStart(),records=data.ky5_state?.records||{},settings=data.ky5_settings||{},pool=data.ky5_pool||{},target=Math.max(pool.items?.length||0,Number(settings.daily)||0),explicit=Object.entries(records).filter(([,record])=>record?.todayDoneDate===today).map(([word])=>word),recent=Object.entries(records).filter(([,record])=>timestampValue(record?.lastSeen)>=start&&!record?.slain).sort((a,b)=>timestampValue(b[1].lastSeen)-timestampValue(a[1].lastSeen)),canRecoverConflict=!explicit.length&&!(pool.completed||[]).length&&target>0&&recent.length>=target,done=explicit.length?explicit:(canRecoverConflict?recent.slice(0,target).map(([word])=>word):[]);if(!done.length)return data;if(canRecoverConflict)for(const word of done)records[word]={...records[word],todayDoneDate:today};const finalTarget=Math.max(target,done.length),items=[...new Set([...done,...(pool.items||[])])].slice(0,finalTarget),completed=[...new Set([...(pool.completed||[]),...done])].filter(word=>items.includes(word));data.ky5_pool={...pool,date:today,mode:pool.mode||settings.mode||'smart',items,completed,locked:pool.locked||[],updatedAt:Date.now()};return data}
export function mergeSnapshots(local,remote){const out={version:2,savedAt:Date.now(),data:{...remote.data,...local.data}};out.data.ky5_state=mergeState(local.data?.ky5_state||{},remote.data?.ky5_state||{});out.data.ky5_settings=mergeSettings(local.data?.ky5_settings||{},remote.data?.ky5_settings||{});out.data.ky5_pool=mergePool(local.data?.ky5_pool,remote.data?.ky5_pool);out.data.ky5_quiz=mergeQuiz(local.data?.ky5_quiz||{},remote.data?.ky5_quiz||{});out.data.ky5_sentence_history=mergeList(local.data?.ky5_sentence_history||[],remote.data?.ky5_sentence_history||[]);recoverTodayPool(out.data);return out}
export function syncSummary(value){const data=value?.data||{},records=data.ky5_state?.records||{},list=Object.values(records),pool=data.ky5_pool||{},sentences=data.ky5_sentence_history||[];return{records:list.length,mastered:list.filter(record=>memoryStage(record)==='mastered').length,verification:list.filter(record=>['recognition','recall','context','relearning'].includes(memoryStage(record))).length,wrong:list.filter(record=>(record.errors||0)>0).length,favorites:list.filter(record=>record.favorite).length,poolDone:(pool.completed||[]).length,poolTotal:(pool.items||[]).length,sentences:Array.isArray(sentences)?sentences.length:0}}
export function applySnapshot(value){if(!value?.data)throw new Error('同步文件格式不正确');for(const[key,data]of Object.entries(value.data)){if(DATA_KEYS.includes(key)&&data!==undefined)localStorage.setItem(key,typeof data==='string'?data:JSON.stringify(data))}localStorage.setItem(META_KEY,JSON.stringify({lastAppliedAt:Date.now(),remoteSavedAt:value.savedAt||0}))}

async function deriveKey(passphrase,syncId){const material=await crypto.subtle.importKey('raw',encoder.encode(passphrase),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:encoder.encode(`shici:${syncId}`),iterations:210000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encrypt(value,config){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(config.passphrase,config.syncId),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(JSON.stringify(value)));return`${b64(iv)}.${b64(new Uint8Array(cipher))}`}
async function decrypt(value,config){const[iv,cipher]=String(value).split('.').map(unb64),key=await deriveKey(config.passphrase,config.syncId),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher);return JSON.parse(decoder.decode(plain))}
async function rpc(config,name,body){const response=await fetch(`${config.endpoint}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:config.anonKey,Authorization:`Bearer ${config.anonKey}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(`云服务返回 ${response.status}: ${(await response.text()).slice(0,180)}`);const text=await response.text();return text?JSON.parse(text):null}

export async function syncNow(config=getSyncConfig()){if(!isConfigured(config))throw new Error('请先完整填写云同步配置');const local=snapshot();const result=await rpc(config,'get_sync',{p_sync_id:config.syncId}),row=Array.isArray(result)?result[0]:result;let merged=local;if(row?.payload){let remote;try{remote=await decrypt(row.payload,config)}catch{throw new Error('无法解密云端数据，请检查同步码和同步密码是否一致')}merged=mergeSnapshots(local,remote);applySnapshot(merged)}const payload=await encrypt(merged,config);await rpc(config,'put_sync',{p_sync_id:config.syncId,p_payload:payload});const summary=syncSummary(merged),meta={lastSyncAt:Date.now(),remoteSavedAt:merged.savedAt,summary};localStorage.setItem(META_KEY,JSON.stringify(meta));return{merged,meta,summary,hadRemote:Boolean(row?.payload)}}

export function exportSyncFile(){const blob=new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`shici-sync-${localDateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export async function importSyncFile(file){const incoming=JSON.parse(await file.text()),merged=mergeSnapshots(snapshot(),incoming);applySnapshot(merged);return merged}

let timer,syncing=false;
export function startAutoSync(onStatus=()=>{}){clearInterval(timer);const run=async()=>{const config=getSyncConfig();if(!isConfigured(config)||config.autoSync===false)return;if(!navigator.onLine){onStatus('offline');return}if(syncing)return;syncing=true;try{onStatus('busy');await syncNow(config);onStatus('ready')}catch(error){onStatus('error',error)}finally{syncing=false}};setTimeout(run,600);timer=setInterval(run,60000);window.addEventListener('offline',()=>onStatus('offline'));window.addEventListener('online',run);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')run()});return run}
