import{KEYS,getSettings,getState,saveState,candidates,findWord}from'./vocabulary-manager.js';
const today=()=>new Date().toISOString().slice(0,10);const read=()=>{try{return JSON.parse(localStorage.getItem(KEYS.pool))}catch{return null}};const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function sources(settings,state){if(settings.mode==='gaokao')return[['gaokao',settings.daily]];if(settings.mode==='kaoyan')return[['kaoyan',settings.daily]];const g=Object.values(state.records).filter(x=>x.source==='gaokao'||x.source==='both'),mastered=g.filter(x=>x.level>=4).length,rate=g.length?mastered/g.length:0;return rate>=.9?[['kaoyan',settings.daily]]:rate>=.7?[['gaokao',Math.min(5,settings.daily)],['kaoyan',Math.max(0,settings.daily-5)]]:[['gaokao',Math.ceil(settings.daily*.6)],['kaoyan',Math.floor(settings.daily*.4)]]}
export function getPool(){const p=read();if(p&&p.date===today())return p;return generatePool()}
export function generatePool(){const settings=getSettings(),state=getState(),items=[];for(const[source,count]of sources(settings,state)){for(const w of shuffle(candidates(source,state)).slice(0,count)){if(!items.includes(w.word))items.push(w.word)}}for(const w of shuffle(candidates('all',state))){if(items.length>=settings.daily)break;if(!items.includes(w.word))items.push(w.word)}items.forEach(word=>{const w=findWord(word);state.records[word]={...(state.records[word]||{}),drawn:true,source:w?.source||'kaoyan',round:state.rounds[w?.source==='gaokao'?'gaokao':'kaoyan']||1}});saveState(state);const pool={date:today(),mode:settings.mode,items,completed:[],locked:[]};save(pool);return pool}
export function save(pool){localStorage.setItem(KEYS.pool,JSON.stringify(pool));return pool}
export function remove(word){const p=getPool();if(p.locked?.includes(word))return p;p.items=p.items.filter(x=>x!==word);return save(p)}
export function toggleLock(word){const p=getPool();p.locked=p.locked||[];p.locked=p.locked.includes(word)?p.locked.filter(x=>x!==word):[...p.locked,word];return save(p)}
export function add(word){const p=getPool();if(findWord(word)&&!p.items.includes(word))p.items.push(word);return save(p)}
export function replace(word){const p=remove(word),state=getState(),next=shuffle(candidates(p.mode==='smart'?'all':p.mode,state)).find(x=>!p.items.includes(x.word));if(next)p.items.push(next.word);return save(p)}
export function fill(){const p=getPool(),s=getSettings(),state=getState();for(const w of shuffle(candidates(s.mode==='smart'?'all':s.mode,state))){if(p.items.length>=s.daily)break;if(!p.items.includes(w.word))p.items.push(w.word)}return save(p)}
