import{KEYS,getSettings,getState,saveState,candidates,findWord}from'./vocabulary-manager.js';
import{coreFirst}from'./core-vocabulary.js';
const today=()=>new Date().toISOString().slice(0,10);const read=()=>{try{return JSON.parse(localStorage.getItem(KEYS.pool))}catch{return null}};const shuffle=a=>coreFirst(a);
function sources(settings,state){if(settings.mode==='gaokao')return[['gaokao',settings.daily]];if(settings.mode==='kaoyan')return[['kaoyan',settings.daily]];const g=Object.values(state.records).filter(x=>x.source==='gaokao'||x.source==='both'),mastered=g.filter(x=>x.level>=4).length,rate=g.length?mastered/g.length:0;return rate>=.9?[['kaoyan',settings.daily]]:rate>=.7?[['gaokao',Math.min(5,settings.daily)],['kaoyan',Math.max(0,settings.daily-5)]]:[['gaokao',Math.ceil(settings.daily*.6)],['kaoyan',Math.floor(settings.daily*.4)]]}
function sourceFor(mode){return mode==='smart'?'all':mode}
function markDrawn(words,state=getState()){words.forEach(word=>{const w=findWord(word);state.records[word]={...(state.records[word]||{}),drawn:true,source:w?.source||'kaoyan',round:state.rounds[w?.source==='gaokao'?'gaokao':'kaoyan']||1}});saveState(state)}
export function getPool(){const p=read();if(p&&p.date===today())return p;return generatePool()}
export function generatePool(){const settings=getSettings(),state=getState(),items=[];for(const[source,count]of sources(settings,state)){for(const w of shuffle(candidates(source,state)).slice(0,count)){if(!items.includes(w.word))items.push(w.word)}}for(const w of shuffle(candidates('all',state))){if(items.length>=settings.daily)break;if(!items.includes(w.word))items.push(w.word)}markDrawn(items,state);const pool={date:today(),mode:settings.mode,items,completed:[],locked:[]};save(pool);return pool}
export function save(pool){localStorage.setItem(KEYS.pool,JSON.stringify(pool));return pool}
export function remove(word){const p=getPool();if(p.locked?.includes(word))return p;p.items=p.items.filter(x=>x!==word);return save(p)}
export function toggleLock(word){const p=getPool();p.locked=p.locked||[];p.locked=p.locked.includes(word)?p.locked.filter(x=>x!==word):[...p.locked,word];return save(p)}
export function add(word){const p=getPool();if(findWord(word)&&!p.items.includes(word)){p.items.push(word);markDrawn([word])}return save(p)}
export function replace(word){const p=remove(word),state=getState(),next=shuffle(candidates(sourceFor(p.mode),state)).find(x=>!p.items.includes(x.word));if(next){p.items.push(next.word);markDrawn([next.word],state)}return save(p)}
export function fill(){const p=getPool(),s=getSettings(),state=getState(),added=[];for(const w of shuffle(candidates(sourceFor(s.mode),state))){if(p.items.length>=s.daily)break;if(!p.items.includes(w.word)){p.items.push(w.word);added.push(w.word)}}if(added.length)markDrawn(added,state);return save(p)}
export function resize(target){const p=getPool(),s=getSettings(),state=getState(),goal=Math.max(1,Math.min(300,Math.floor(Number(target)||s.daily||20)));p.mode=s.mode;p.completed=p.completed||[];p.locked=p.locked||[];const protectedWords=new Set([...p.completed,...p.locked]);for(let i=p.items.length-1;p.items.length>goal&&i>=0;i--){if(!protectedWords.has(p.items[i]))p.items.splice(i,1)}const added=[];for(const w of shuffle(candidates(sourceFor(s.mode),state))){if(p.items.length>=goal)break;if(!p.items.includes(w.word)){p.items.push(w.word);added.push(w.word)}}if(added.length)markDrawn(added,state);return save(p)}
export function extend(count){const p=getPool(),state=getState(),added=[],target=p.items.length+Math.max(0,Number(count)||0);for(const w of shuffle(candidates(sourceFor(p.mode),state))){if(p.items.length>=target)break;if(!p.items.includes(w.word)){p.items.push(w.word);added.push(w.word)}}if(added.length)markDrawn(added,state);save(p);return added}
